### ISSUE TITLE
Support for `IF ELSE END`

### ISSUE THREAD

**Issue by zedtux** [earthly/sublimetext-earthly-syntax#4]
As of writing the syntax is not colored for `IF` and `ELSE`:

![Screenshot from 2023-04-11 09 18 51](https://user-images.githubusercontent.com/478564/231085287-1d38ac9f-f04a-47f6-9988-022128817d00.png)

**Comment by Velutas** [comment]
Support for these commands has now been added as of https://github.com/earthly/sublimetext-earthly-syntax/pull/5 

Thanks for bringing up this issue.
